trigger:
  branches:
    include:
    - production

variables:
  imageRepository: 'homeapi'
  dockerfilePath: 'src/HomeApi/Dockerfile'
  tag: $[counter('version', 0)] # Auto-incrementing version

stages:
- stage: Build
  displayName: Build and Push
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acrServiceConnection'
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
          latest
    
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'azureServiceConnection'
        KeyVaultName: 'your-key-vault'
        SecretsFilter: 'external-prod-secret'
    
    - script: |
        echo "##vso[task.setvariable variable=imageTag;isOutput=true]$(tag)"
      name: setImageTag

- stage: Deploy
  displayName: Update Flux
  dependsOn: Build
  jobs:
  - job: UpdateManifest
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      imageTag: $[ dependencies.Build.outputs['setImageTag.imageTag'] ]
    steps:
    - checkout: self
      fetchDepth: 0
    
    - script: |
        sed -i "s/newTag: .*/newTag: $(imageTag)/" clusters/production/homeapi/kustomization.yaml
        sed -i "s|image: .*|image: your-acr.azurecr.io/homeapi:$(imageTag)|" clusters/production/homeapi/deployment.yaml
      displayName: 'Update image tags'
    
    - script: |
        git config --global user.email "azuredevops@example.com"
        git config --global user.name "Azure DevOps"
        git add clusters/production/homeapi/*
        git commit -m "Update image to version $(imageTag)"
        git push origin HEAD:production
      displayName: 'Commit and push changes'