apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeui-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: homeui.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeui
            port:
              number: 80