apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeapi
  template:
    metadata:
      labels:
        app: homeapi
      annotations:
        fluxcd.io/automated: "true"
    spec:
      containers:
      - name: homeapi
        image: homeapi:net9
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        envFrom:
        - secretRef:
            name: external-prod-secret
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10