apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeapi-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: homeapi.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeapi
            port:
              number: 80