apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

secretGenerator:
  - name: external-prod-secret
    type: Opaque
    literals:
      - IdentityClientSettings__PublicKey=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2MUsrNVNURTlONlFmd0c0MDloZAprR0k1bWhXU2FJUWc0ZXhCMnQ1cXY3WUh5ZExFM25vY1hySGtCN3pzMkhOZ0piRGJKaDd0ZTNYVWxXWXIwdlFhCitYM0hsUVlPaHF0aDU4ZWc0YzU5bDJPRFMvYTBkdnVweUJURGlicDBqUWxNZ2VmTFVNRDlSUEZ2UXRxeTEydzUKSCs1ZTBjZEpFemNpRXdSL2ZGTlJsemV0ODliTkdURFR5MU04bmcyMlc4dDIvRHdpb2s1U2I0VWMxMDR1Qk5Xbgpha2FGSU5MaU9zWlV5UDZ0ZzdOYVoxWUkyOGhLMXVCY0pmdm1qbFBwL2YvcTFOVXhicktrN0pjc1VJVWVRVDBpCmlLL2pleEpFSWZBWURBR0UwMmdQVlBQRVRCL0twSkxFNVhuamZLdlBVdmpyb0JRQkZqamVTdlpPR3FmZzFxSlgKendJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t