apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

secretGenerator:
  - name: external-prod-secret
    type: Opaque
    literals:
      - IdentityClientSettings__PublicKey=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS1cbk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdjFLKzVTVEU5TjZRZndHNDA5aGRcbmtHSTVtaFdTYUlRZzRleEIydDVxdjdZSHlkTEUzbm9jWHJIa0I3enMySE5nSmJEYkpoN3RlM1hVbFdZcjB2UWFcbitYM0hsUVlPaHF0aDU4ZWc0YzU5bDJPRFMvYTBkdnVweUJURGlicDBqUWxNZ2VmTFVNRDlSUEZ2UXRxeTEydzVcbkgrNWUwY2RKRXpjaUV3Ui9mRk5SbHpldDg5Yk5HVERUeTFNOG5nMjJXOHQyL0R3aW9rNVNiNFVjMTA0dUJOV25cbmFrYUZJTkxpT3NaVXlQNnRnN05hWjFZSTI4aEsxdUJjSmZ2bWpsUHAvZi9xMU5VeGJyS2s3SmNzVUlVZVFUMGlcbmlLL2pleEpFSWZBWURBR0UwMmdQVlBQRVRCL0twSkxFNVhuamZLdlBVdmpyb0JRQkZqamVTdlpPR3FmZzFxSlhcbnp3SURBUUFCXG4tLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=